-- VOTESS database. Import in Hostinger hPanel > Databases > phpMyAdmin > Import.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS leads (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ref VARCHAR(24) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  preferred_contact VARCHAR(20) NOT NULL DEFAULT 'email',
  preferred_time VARCHAR(40) DEFAULT NULL,
  company VARCHAR(150) DEFAULT NULL,
  designation VARCHAR(100) DEFAULT NULL,
  website VARCHAR(200) DEFAULT NULL,
  org_size VARCHAR(40) DEFAULT NULL,
  country VARCHAR(80) DEFAULT NULL,
  state VARCHAR(80) DEFAULT NULL,
  city VARCHAR(80) DEFAULT NULL,
  purpose VARCHAR(30) NOT NULL,
  sub_interest VARCHAR(120) DEFAULT NULL,
  budget VARCHAR(40) DEFAULT NULL,
  timeline VARCHAR(40) DEFAULT NULL,
  heard_from VARCHAR(60) DEFAULT NULL,
  message TEXT NOT NULL,
  consent_privacy TINYINT(1) NOT NULL DEFAULT 0,
  consent_marketing TINYINT(1) NOT NULL DEFAULT 0,
  source_url VARCHAR(255) DEFAULT NULL,
  utm_source VARCHAR(80) DEFAULT NULL,
  utm_medium VARCHAR(80) DEFAULT NULL,
  utm_campaign VARCHAR(80) DEFAULT NULL,
  ip VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  status ENUM('new','contacted','qualified','won','lost','spam') NOT NULL DEFAULT 'new',
  admin_mail_sent TINYINT(1) NOT NULL DEFAULT 0,
  user_mail_sent TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT DEFAULT NULL,
  KEY idx_email (email), KEY idx_purpose (purpose), KEY idx_status (status), KEY idx_created (created_at), KEY idx_ip (ip, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_ref VARCHAR(24) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  gateway ENUM('razorpay','cashfree','payu','easebuzz','upi') NOT NULL,
  gateway_order_id VARCHAR(80) DEFAULT NULL,
  gateway_payment_id VARCHAR(80) DEFAULT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'INR',
  status ENUM('created','pending_verification','paid','failed') NOT NULL DEFAULT 'created',
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  purpose VARCHAR(150) DEFAULT NULL,
  invoice_no VARCHAR(40) DEFAULT NULL,
  utr VARCHAR(30) DEFAULT NULL,
  ip VARCHAR(45) DEFAULT NULL,
  raw_response MEDIUMTEXT DEFAULT NULL,
  KEY idx_status (status), KEY idx_gw_order (gateway_order_id), KEY idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
